version: "3"
volumes:
  postgres-data:
services:
  bowling:
    build: .
    ports:
      - "3000:3000"
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    volumes:
      - .:/usr/src/bowling/
      - /app/tmp
  db:
    image: "postgres"
    environment:
      POSTGRES_USER: bowling
      POSTGRES_PASSWORD: bowling
      POSTGRES_DB: bowling_development
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"